# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='user',
        ),
        migrations.AddField(
            model_name='items',
            name='user',
            field=models.ManyToManyField(to='wish_list.Users'),
        ),
    ]
